import Component, {tracked} from "@glimmer/component";
import moment from 'moment'
const {log, clear} = console;
//todo
/**
 * Data
 * Real Data
 * Handle menu icon
 * responsive: orientation, tablets, monitor,
 * **/

const missionaryData = {
  name: `Rev Emmanuel Singh`,
  age: 35,
  birthday: '1982-02-17',
  wife: 'Mrs Sonnali Singh',
  text: [`Rev Emmanuel Singh is the Missionary Pastor of Covenant Evangelical Reformed Church (CERC).`,
  `He is currently working in the mission field of Kolkata, and Lord Willing, instituted the mission field as a church there`],
  imgArray: [
    'assets/emmanuel-wo-bg.png',
    'assets/emmanuel-and-sonali-singh-kolkota.png'
  ],
  link: `https://cksaltshakers.wordpress.com/2017/04/01/interview-with-rev-emmanuel-singh-i/`
}
  //`Rev Emmanuel Singh`;

const sectionItems = [
  'CERC',
  'Main',
  'History',
  'The Fellowship',
  'Sermon Outlines',
  'The Missionary',
  'Letters',
  'Make a Friend',
  'Prayer Requests',
  'Updates',
  'Birthdays',
  'Encourage Program',
  'Kolkata'
];


let historySectionData = {
  img: `assets/sanctuaryLARGE.jpg`,
  text: [`In 2009, Rev Emmanuel was connected to PRCA ministers while he was working for Para-church organizations “Operation Mobilisation” (OM) and “Back to the Bible” Radio Broadcast. 
  During this time Rev Emmanuel was sharing the Reformed Gospel to the Bengali people in Kolkata as well as in the village’s area. 
  As a result of the preaching of the gospel, many responded to the Reformed faith to learn more about Reformed doctrines. 
  Rev Emmanuel then started Bible cell Groups so that through regular teaching a Church may be instituted.`,
  `Until 2010, Rev Emmanuel was worshiping with “Brethren Assembly” but after coming to the Reformed faith, he did not find any reformed church in the Kolkata area. 
  While there was one Mizo Presbyterian Church, they do not hold the Reformed Confessions (such as the Three Forms of Unity) or the Westminster Larger/Shorter Catechism. 
  They were thus doing Bible study on the Lord’s Day. 
  In 2013 they started to worship the Lord as a fellowship. 
  From 2015 onwards, CERC Singapore started to oversee the work in Kolkata and now they are growing be an instituted church, Lord willing, in the next few years.`]
};

let fellowshipData = [
  'Stayan Park, Joka, Kolkata, (southern part of Kolkata)',
  'Activities:',
  'Sunday evening at 5:30 PM',
  'Pre-confession Class to start soon',
  'Friday Night Bible studies',
  'Gospel tracts distribution',
  'Meeting individuals for personal Evangelism',
  'Visiting members’ house for cottage meeting',
  'Gospel Preaching Seminar',
  'Translation of Reformed Confessions',
  'Joys:',
  'to worship the Lord based on Reformed principles',
  'good unity among them',
  'willing to share the Gospel',
  'Struggles:',
  'having a meeting place'
];

let sermonsData = {
  '2017-04-04|0': {
    date: '10.04.2017',
    className: null,
    sermonTitle: 'The Incarnation of the Son of God',
    scriptureText: '',
    sermonText: 'B.C. Article 18',
    sermonPoints: [
      'The Climax of History',
      'The Reality of the Incarnation',
      'He is Truly Both Man & God',
      'Rejection of Errors - Anabaptists Heresy Concerning Christ\'s Incarnation'
    ]
  },
  '2017-06-11|0': {
    date: '17.04.2017',
    className: null,
    sermonTitle: 'WHERE HAS THE POWER GONE? (PENTECOST)',
    scriptureText: 'Acts 1:8, 2 Timothy 1:7, Colossian 1:11',
    sermonText: 'Judges 6: 12-13',
    sermonPoints: [
      'The Early Christian Had Great Spiritual Power',
      'Why Do We Not have Such Power Today? Some Reasons For Current Lack',
      'Conclusion: Evaluate Ourselves (2 Cor 10:12)'
    ]
  },
  '2017-06-18|0': {
    date: '24.04.2017',
    className: null,
    sermonTitle: 'THE ESSENCE OF KINGDOM LIFE',
    scriptureText: '',
    sermonText: 'John 3:1-10, Matthew 6:33, Matthew 6:9',
    sermonPoints: [
      'Seeing The the Kingdom of God - Regenerated by God',
      'Seeking the the Kingdom of God - As a Supreme Priority in Our Life',
      'Praying for the Kingdom of God - Our Calling to Pray'
    ]
  }
};

let personsData = {
  'Sudip Van Dyker': {
    birthday: '24-06',
    name: 'Sudip Van Dyker',
    img: 'assets/profile-circle-2.png',
    text: `Sudip Lorem ipsum dolor. Sit amet vitae sed mauris et.
  Sed erat libero ullamcorper quis vestibulum vel optio in nibh semper blandit.
  Aenean elementum purus nulla libero nibh. Vitae bibendum enim sollicitudin dicta quis.
  Ipsum duis officia. Diam facere id. Dis augue vivamus. Vitae odio eu dictumst sapien libero ornare in porttitor
  lorem risus neque consequat vitae aenean taciti non pede vitae erat libero ullamcorper arcu eu et mi etiam.
  Eros mollis sed. Sem elit consequat phasellus lacinia nam adipiscing sed porttitor. Pede justo et sed nullam in.
  Aliquet varius ut lorem neque mollis.`
  },
  'Ranjit Supramalam': {
    birthday: '24-06',
    name: 'Ranjit Supramalam',
    img: 'assets/profile-circle-5.png',
    text: `Ranjit Lorem ipsum dolor. Sit amet vitae sed mauris et.
  Sed erat libero ullamcorper quis vestibulum vel optio in nibh semper blandit.
  Aenean elementum purus nulla libero nibh. Vitae bibendum enim sollicitudin dicta quis.
  Ipsum duis officia. Diam facere id. Dis augue vivamus. Ranjit Lorem ipsum dolor. Sit amet vitae sed mauris et.
  Sed erat libero ullamcorper quis vestibulum vel optio in nibh semper blandit.
  Aenean elementum purus nulla libero nibh. Vitae bibendum enim sollicitudin dicta quis.
  Ipsum duis officia. Diam facere id. Dis augue vivamus. Ranjit Lorem ipsum dolor. Sit amet vitae sed mauris et.
  Sed erat libero ullamcorper quis vestibulum vel optio in nibh semper blandit.
  Aenean elementum purus nulla libero nibh. Vitae bibendum enim sollicitudin dicta quis.
  Ipsum duis officia. Diam facere id. Dis augue vivamus.`
  },
  'Monisha Puraj': {
    birthday: '15-06',
    name: 'Monisha Puraj',
    img: 'assets/profile-circle-6.png',
    text: ``
  },
  'Johnny Manakam': {
    birthday: '20-06',
    name: 'Johnny Manakam',
    img: 'assets/profile-circle-1.png',
    text: ``
  },
  'Manjan Pillai': {
    birthday: '24-02',
    name: 'Manjan Pillai',
    img: 'assets/profile-circle-3.png',
    text: ``
  },
  'Bharath Singh': {
    birthday: '24-03',
    name: 'Bharath Singh',
    img: 'assets/profile-circle-4.jpg',
    text: ``
  },
  'Priyanka Puja': {
    birthday: '24-09',
    name: 'Priyanka Puja',
    img: 'assets/profile-circle-7.jpeg',
    text: ``
  },
  'Kala Monashurat': {
    birthday: '24-12',
    name: 'Kala Monashurat',
    img: 'assets/profile-circle-8.jpeg',
    text: ``
  }
};

let personsKeys = Object.keys(personsData);


let ourLettersData = {
  '2017-03': {
    date: '2017-03',
    letterContent: `March Our Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem`,
    pdfLink: 'March'
  },
  '2017-04': {
    date: '2017-04',
    letterContent: `April Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem`,
    pdfLink: 'April'
  },
  '2017-05': {
    date: '2017-05',
    letterContent: `May Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem`,
    pdfLink: 'May'
  },
  '2017-12': {
    date: '2017-12',
    letterContent: `December Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem`,
    pdfLink: 'December'
  }
};


let theirLettersData = {
  '2017-03': {
    date: '2017-03',
    letterContent: `March their Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch their Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch their Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem`,
    pdfLink: 'March'
  },
  '2017-04': {
    date: '2017-04',
    letterContent: `April their Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch their Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch their Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem`,
    pdfLink: 'April'
  },
  '2017-05': {
    date: '2017-05',
    letterContent: `May their Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch their Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch their Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem`,
    pdfLink: 'May'
  },
  '2017-12': {
    date: '2017-12',
    letterContent: `December their Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch their Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem
      arch their Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
      Aenean commodo ligula eget dolor. Aenean massa. 
      Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. 
      Donec quam felis, ultricies nec, pellentesque eu, pretium quis, 
      sem Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem`,
    pdfLink: 'December'
  }
};

let imageGalleryData = [
    'assets/sanctuaryLarge.jpg',
    'assets/scenery.jpg'
];


let prayerRequestsData = {
  constant: [
    {
      content: 'Prayer Requests Constant 1',
      valid: true,
      date: '2017-04-09'
    }, {
      content: 'Prayer Requests Constant 2',
      valid: false,
      date: '2017-06-09'
    }, {
      content: 'Prayer Requests Constant 3',
      valid: true,
      date: '2017-07-09'
    },
    {
      content: 'Prayer Requests Constant 4',
      valid: true,
      date: '2017-07-21'
    }
  ],
  adHoc: [
    {
      content: 'Prayer Requests ad-hoc 1',
      valid: true,
      date: '2017-07-21'
    }, {
      content: 'Prayer Requests ad-hoc 2',
      valid: true,
      date: '2017-07-21'
    }, {
      content: 'Prayer Requests ad-hoc 3 invalid',
      valid: false,
      date: '2017-07-21'
    }, {
      content: 'Prayer Requests ad-hoc 4',
      valid: true,
      date: '2017-07-21'
    }, {
      content: 'Prayer Requests ad-hoc 5',
      valid: true,
      date: '2017-07-21'
    }, {
      content: 'Prayer Requests ad-hoc 6 invalid',
      valid: false,
      date: '2017-07-21'
    }, {
      content: 'Prayer Requests ad-hoc 7',
      valid: true,
      date: '2017-07-21'
    }, {
      content: 'Prayer Requests ad-hoc 8',
      valid: true,
      date: '2017-07-21'
    }
  ]
  //end of array
};


let updatesData = [
  {
    content: 'Updates 1',
    valid: true,
    date: '2017-04-09'
  }, {
    content: 'Updates 1',
    valid: true,
    date: '2017-04-09'
  }, {
    content: 'Updates 2 -invalid',
    valid: false,
    date: '2017-04-09'
  }, {
    content: 'Updates 1',
    valid: true,
    date: '2017-04-09'
  }, {
    content: 'Updates 1',
    valid: true,
    date: '2017-04-09'
  }, {
    content: 'Updates 5 -invalid',
    valid: false,
    date: '2017-04-09'
  }, {
    content: 'Updates 1',
    valid: true,
    date: '2017-04-09'
  }, {
    content: 'Updates 1',
    valid: true,
    date: '2017-04-09'
  };


  //////////data end

const dasherizedTitle = (title) => {
  const trimmedTitle = title.trim().toLowerCase();
  const theLessTitle = trimmedTitle.replace(/^(the\s)/ig, '');
  const dashedTitle = theLessTitle.replace(/\s/g, '-');
  return dashedTitle;
};

const treatedMenuItems = (array) => {
  return array.map((section, index) => {
    const lowerCaseSection = (typeof section === 'string') ? section.toLowerCase() : section;

    switch(lowerCaseSection) {
      case `cerc`:
        return {
          id: lowerCaseSection,
          link: `https://www.cerc.org.sg`,
          class: ``,
          title: section,
          shortTitle: section,
        };
        break;
      case `main`:
        return {
          id: lowerCaseSection,
          link: ``,
          class: `header-section`,
          title: `The Fellowship of Kolkata`,
          shortTitle: section,
        };
        break;
      case `the missionary`:
        return {
          id: dasherizedTitle(section),
          link: ``,
          class: `${dasherizedTitle(section)}-section`,
          title: missionaryData.name,
          shortTitle: section,
        };
        break;
      default:
        return {
          id: dasherizedTitle(section),
          link: ``,
          class: `${dasherizedTitle(section)}-section`,
          title: section,
          shortTitle: section,
        };
    }
  });
};


const idMapGenerator = (array) => {
  if (!Array.isArray(array)) return {array: array};
  return array.reduce((acc, item, index) => {
    if (item.id === undefined || item.id === null) return Object.assign(acc, {index: item});
    return Object.assign(acc, {[item.id]: item});
  }, {});
};

const compose = (acc, fn) => {
  if (typeof fn !== 'function') return acc;
  return fn(acc);
};


const singlePropertyCallback = (property) => (x) => {
  if (x[property] !== undefined && x[property] !== null) {
    return x[property];
  };
};

const validPropCB = singlePropertyCallback('valid');
const contentPropCB = singlePropertyCallback('content');
const maxNumber = () => 8;

const filterSliceMap = (array) => ([startIndex, endIndex]) => {
  return array.filter(validPropCB).slice(startIndex, endIndex).map(contentPropCB);
};

const getPrayerRequestsData = (maxNum) => (prayerRequests) => {
  const maxNumber = maxNum; //need to change based on screen size
  const constantArray = filterSliceMap(prayerRequests.constant)([-maxNumber]);
  const adHocSliceStartIndex = (maxNumber - constantArray.length) * -1;
  const adHocArray = filterSliceMap(prayerRequests.adHoc)([adHocSliceStartIndex]);
  return [...constantArray, ...adHocArray];
};

const getUpdatesData = (maxNum) => (updates) => {
  const maxNumber = maxNum;
  return filterSliceMap(updates)([-maxNumber]);
};

/********************************************
 *
 *
 *
 ********************************************/

export default class KolkataInterestPage extends Component {
  @tracked gray = '';

  mainHeader = 'The Mission Field of Kolkata';

  get sections() {
    const sectionsObj = [treatedMenuItems, idMapGenerator].reduce(compose, sectionItems);
    log(`something special`);
    return sectionsObj;
  }


  turnGray(bool) {
    this.gray = bool ? 'gray' : '';
  }

  actionHandler(action, params) {
    this[action](params);
  }

  historySectionData = historySectionData;

  get personsDataForAboutSection() {

    const personsArray = personsKeys.map((person) => personsData[person].img);
    return personsArray;
  }

  missionaryData = missionaryData;

  sermonsData = sermonsData;

  fellowshipData = fellowshipData;

  theirLetters = theirLettersData;
  ourLetters = ourLettersData;
  imageGalleryData = imageGalleryData;

  get personsDataForFriendSection() {
    const personsKeysArray = personsKeys.filter((person) => personsData[person].text).reverse();
    const personsArray = personsKeysArray.reduce((acc, key) => acc.concat(personsData[key]), []);
    return personsArray;
  };

  get personsDataForBirthdaySection() {
    const keysArray = Object.keys(personsData);
    const dataArray = keysArray.map(key => personsData[key]);
    return dataArray;
  }

  prayerRequestsArray = getPrayerRequestsData(maxNumber())(prayerRequestsData);

  updatesArray = getUpdatesData(maxNumber())(updatesData);
}
